services:
    frontend:
        build:
            context: ./docker
            dockerfile: Dockerfile
        environment:
            VITE_API_URL: ${VITE_API_URL:-http://localhost:8080}
        ports:
            - "3000:80"
